x = input('type something: ')
print(f'O tipo de dado desse valor é {type(x)}')
print(f'É numérico? {x.isnumeric()}')
print(f'Possuí espaços? {x.__contains__(" ")}')
print(f'Possuí somente espaços? {x.isspace()}')
print(f'É alfabético? {x.isalpha()}')
print(f'É alfanumérico? {x.isalnum()}')
print(f'Esta em maiúsculas? {x.isupper()}')
print(f'Está em minúsculas? {x.islower()}')
print(f'Está capitalizada? {x.istitle()}')
